name: Deploy Surfingkeys config to gist
on: 
  push:
    branches:
      - test

jobs:
  deploy:
    name: Deploy surfingkeys.js to gist
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy
        uses: exuanbo/actions-deploy-gist@v1
        with:
          token: ${{ secrets.GIST_DEPLOY_TOKEN }}
          gist_id: 04d1b579f43dedceeb6f6b0b2e6f8e18
          gist_file_name: surfingkeys.js
          file_path: ./surfingkeys.js
